/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package bw.study.examples.camel

import groovy.util.logging.Slf4j
import org.apache.camel.CamelContext
import org.apache.camel.Exchange
import org.apache.camel.ProducerTemplate
import org.apache.camel.builder.RouteBuilder
import org.apache.camel.impl.DefaultCamelContext
import org.apache.camel.impl.engine.DefaultStreamCachingStrategy

@Slf4j
class CamelMessageTest {

    static void main(String[] args) {
        System.out.println('This is an example of SNMP Trap Listener')
        CamelContext camel = new DefaultCamelContext()
        camel.getShutdownStrategy().tap {
            it.setShutdownRoutesInReverseOrder(true)
            it.setShutdownNowOnTimeout(true)
            it.setTimeout(1)
        }
        camel.allowUseOriginalMessage = true
        camel.streamCachingStrategy = new DefaultStreamCachingStrategy(spoolThreshold: -1)
        camel.getGlobalOptions().put(Exchange.LOG_EIP_NAME, "bw.study.examples");
        RouteBuilder.addRoutes(camel, {
            it
                    .from('jetty:http://0.0.0.0:8080/test')
                    .routeId('direct.test')
                    .to("log:bw.study.examples?showAll=true&multiline=true&showStreams=true")
                    .process {
                       it.in.setHeader('test', 'stream')
                    }
                    .convertBodyTo(String)
                    .to("log:bw.study.examples?showAll=true&multiline=true")
                    .process {
                        sleep(1000)
                    }
        })
        camel.addShutdownHook {
            System.out.println('Exiting')
        }
        camel.start()
        ProducerTemplate producerTemplate = camel.createProducerTemplate()
        producerTemplate.sendBody('http://localhost:8080/test',"My Test body")
        Thread.sleep(1 * 60 * 1000)
        camel.stop()
    }

}
