/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package bw.study.examples.camel

import groovy.util.logging.Slf4j
import org.apache.camel.CamelContext
import org.apache.camel.Exchange
import org.apache.camel.builder.RouteBuilder
import org.apache.camel.impl.DefaultCamelContext

import java.time.Instant

@Slf4j
class SnmpManager {

    static void main(String[] args) {
        System.out.println('This is an example of SNMP Trap Listener')
        CamelContext camel = new DefaultCamelContext()
        camel.getShutdownStrategy().tap {
            it.setShutdownRoutesInReverseOrder(true)
            it.setShutdownNowOnTimeout(true)
            it.setTimeout(1)
        }
        camel.getGlobalOptions().put(Exchange.LOG_EIP_NAME, "bw.study.examples");
        RouteBuilder.addRoutes(camel, {
            it
                    .from("snmp:0.0.0.0:10162?protocol=tcp&type=TRAP&snmpVersion=1&securityLevel=1")
                    .routeId('snmp.trap.listener')
                    .to("log:bw.study.examples?showAll=true&multiline=true")
        })
        camel.addShutdownHook {
            System.out.println('Exiting')
        }
        camel.start()
        Thread.sleep(3600000)
        camel.stop()
    }

}
