/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package bw.study.examples.camel


import groovy.util.logging.Slf4j
import org.apache.camel.CamelContext
import org.apache.camel.Exchange
import org.apache.camel.builder.RouteBuilder
import org.apache.camel.impl.DefaultCamelContext

import java.text.SimpleDateFormat
import java.time.Instant

@Slf4j
class JettyServer {

    static void main(String[] args) {
        int count =1
        CamelContext camel = new DefaultCamelContext()
        camel.getShutdownStrategy().tap {
            it.setShutdownRoutesInReverseOrder(true)
            it.setShutdownNowOnTimeout(true)
            it.setTimeout(1)
        }
        camel.getGlobalOptions().put(Exchange.LOG_EIP_NAME, "bw.study.examples");
        RouteBuilder.addRoutes(camel, {
            it
            .from("jetty:http://0.0.0.0:18080/bw/test/example")
            .routeId('jetty.service')
            .convertBodyTo(java.lang.String)
            .to("log:bw.study.examples?showAll=true&multiline=true")
            .process {
                it.in.headers['CamelFileName'] = 'msg-' + Instant.now().toString() + '.txt'            }
            //.setHeader('CamelFileName').simple("msg-${date:now:yyyyMMddHHmmssSSS}.txt")
            .to("file:receivedMessages?charset=utf-8")
        })
        camel.addShutdownHook {
            sleep(60000)
            camel.shutdown()
        }
        camel.start()
        Thread.sleep(70000)
    }
}
