/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package bw.study.examples.camel

import groovy.util.logging.Log4j2
import groovy.util.logging.Slf4j
import org.apache.camel.CamelContext
import org.apache.camel.Exchange
import org.apache.camel.builder.RouteBuilder
import org.apache.camel.impl.DefaultCamelContext
import org.apache.camel.spi.ShutdownStrategy

@Slf4j
class RabbitMQConsumer {

    static void main(String[] args) {
        int count =1
        CamelContext camel = new DefaultCamelContext()
        camel.getShutdownStrategy().tap {
            it.setShutdownRoutesInReverseOrder(true)
            it.setShutdownNowOnTimeout(true)
            it.setTimeout(1)
        }
        camel.getGlobalOptions().put(Exchange.LOG_EIP_NAME, "bw.study.examples");
        RouteBuilder.addRoutes(camel, {
            it
            .from("rabbitmq:mytest?addresses=localhost:5672&username=guest&password=guest")
            .routeId('rabbitmq.client.consumer')
            .to("log:bw.study.examples?showAll=true&multiline=true")
        })
        camel.addShutdownHook {
            camel.shutdown()
        }
        camel.start()
        Thread.sleep(300000)
        camel.stop()
    }
}
